### ISSUE TITLE
`PredictionStatusObject` type not exported

### ISSUE THREAD

**Issue by archasek** [Zebreus/replicate-api#2]
Seems that `PredictionStatusObject` type is not exported. Not a big deal I guess, but would be helpful.

My case:
`export async function requestReplicate(): Promise<PredictionStatusObject> {}`

**Comment by archasek** [comment]
Perhaps I'm a bit confused, but this time my IDE imported it (however, from the nested path: `replicate-api/dist/helpers/convertPrediction`). 

Closing then, until I find it's a problem :D

**Comment by zebreus** [comment]
For now I only export the functions in `index.js`, but not the types. I have looked around a bit, it seems to be common practice to also have the types that are relevant for library users directly exported from there.

I added them to the index file, so it should work as expected with the latest version.
